alembic = "^1.6.2"
flask_login = "^0.5.0"
flask_migrate = "^3.0.0"
werkzeug = "^2.0.1"
wtforms = "^2.3.3"
wtforms_components = "^0.10.5"
sqlalchemy = "^1.4.15"
flask_wtf = "^0.14.3"
flask = "^2.0.0"
flask_sqlalchemy = "^2.5.1"
python-dotenv = "^0.17.1"
