"""'event_datetime'

Revision ID: 1acd8925efef
Revises: 633e06b0dd7b
Create Date: 2021-05-23 21:54:14.338448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acd8925efef'
down_revision = '633e06b0dd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
