"""event date and time

Revision ID: 633e06b0dd7b
Revises: c721b97424cf
Create Date: 2021-05-22 18:06:20.890761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633e06b0dd7b'
down_revision = 'c721b97424cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_date', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('event_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_event_event_date'), 'event', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_event_time'), 'event', ['event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_event_time'), table_name='event')
    op.drop_index(op.f('ix_event_event_date'), table_name='event')
    op.drop_column('event', 'event_time')
    op.drop_column('event', 'event_date')
    # ### end Alembic commands ###
