"""empty message

Revision ID: 956dc2d15f0d
Revises: 1acd8925efef
Create Date: 2021-05-25 09:49:25.459657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956dc2d15f0d'
down_revision = '1acd8925efef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_datetime', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_event_event_date')
        batch_op.drop_index('ix_event_event_time')
        batch_op.create_index(batch_op.f('ix_event_event_datetime'), ['event_datetime'], unique=False)
        batch_op.drop_column('event_time')
        batch_op.drop_column('event_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('event_time', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_event_event_datetime'))
        batch_op.create_index('ix_event_event_time', ['event_time'], unique=False)
        batch_op.create_index('ix_event_event_date', ['event_date'], unique=False)
        batch_op.drop_column('event_datetime')

    op.create_table('_alembic_tmp_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('event_body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
